/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.devopsfordefense.cm101;

import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        NumGen ng = new NumGen();
        List<Double> numbers = ng.generate();
        System.out.println("Generated " + numbers.size() + " numbers.");
        
        System.out.println(new App().getGreeting());
    }
}
