/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.devopsfordefense.cm101;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Disabled;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Disabled("removed functionallity") 
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
